backend:
  workers: 1
  queue: 100
  retries: 3
  backoff: 5
  showcounter: 5
kafka:
  # begining: true
  broker: "10.0.30.249:9092"
  consumergroup: "k2httpd"
  topics:
    - test
http:
  url: "http://localhost:8080"
  batchsize: 100
  batchtimeout: 500
  deflate: true
